apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
        - name: iris-container
          image: your-dockerhub-username/iris-api:latest
          ports:
            - containerPort: 80
